FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
# FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS base
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore
# RUN dotnet restore "pix-hub-api.csproj"

COPY . ./

# install ef to run migrations
RUN dotnet tool install --global dotnet-ef
ENV PATH="${PATH}:/root/.dotnet/tools"

CMD ["dotnet", "ef", "database", "update"]